### ISSUE TITLE
MissingPluginException(No implementation found for method hasPermissions on channel plugins.builttoroam.com/device_calendar)

### ISSUE THREAD

**Issue by Sri-Madhan** [builttoroam/device_calendar#285] opened 2021-03-22 08:18 UTC
i need to retrieve Calendars events in my app 

the below function i have used :

_retrieveCalendars()async{

    try {
      var permissionsGranted = await _deviceCalendarPlugin.hasPermissions();
      if (permissionsGranted.isSuccess && !permissionsGranted.data) {
        permissionsGranted = await _deviceCalendarPlugin.requestPermissions();
        if (!permissionsGranted.isSuccess || !permissionsGranted.data) {
          return;
        }
      }

      final calendarsResult = await _deviceCalendarPlugin.retrieveCalendars();
      _calendars=calendarsResult.data;
      for(int c=0;c<_calendars.length;c++){
        calendarName.add(_calendars[c].name);
      }

    } on PlatformException catch (e) {
      print(e);
    }

  }

**Comment by andzejsw** [comment] 2021-04-27 06:44
Does this issue appear with latest dev version? And on which device?

**Comment by andzejsw** [comment] 2021-05-21 09:20
Possible duplicate of https://github.com/builttoroam/device_calendar/issues/303. Closing since issue 303 is resolved.

**Closed by andzejsw** 2021-05-21 09:20 UTC
