### ISSUE TITLE
Suddenly get strange kotlin.KotlinNullPointerException when trying to store an event.

### ISSUE THREAD

**Issue by severin13** [builttoroam/device_calendar#317] opened 2021-07-13 12:21 UTC
I suddenly receive this error when trying to store events. I verified the calendarId I am using about ten times. I just built the simplest app and retried but do get the same error. Ironically, when I clone de device_calendar repo from here, the app works without any problem, so my local setup with VS Code on Windows does not seem to be the problem. Is there anything I am missing when creating my event? I do not get an error when I create the event without start and end, however I still get null as a return of the createOrUpdateEvent method. I also tried it with different TZDateTime constructors but none of them seems to work... Many thanks in advance for any help with this!

**ERROR:**
Performing hot restart...                                               
Restarted application in 817ms.
E/MethodChannel#plugins.builttoroam.com/device_calendar(23830): Failed to handle method call
E/MethodChannel#plugins.builttoroam.com/device_calendar(23830): kotlin.KotlinNullPointerException
E/MethodChannel#plugins.builttoroam.com/device_calendar(23830):         at com.builttoroam.devicecalendar.DeviceCalendarPlugin.parseEventArgs(DeviceCalendarPlugin.kt:151)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23830):         at com.builttoroam.devicecalendar.DeviceCalendarPlugin.onMethodCall(DeviceCalendarPlugin.kt:108)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23830):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23830):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23830):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)E/MethodChannel#plugins.builttoroam.com/device_calendar(23830):         at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23830):         at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23830):         at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23830):         at android.app.ActivityThread.main(ActivityThread.java:7664)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23830):         at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23830):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)E/MethodChannel#plugins.builttoroam.com/device_calendar(23830):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter (23830): PlatformException(error, null, null, kotlin.KotlinNullPointerException
I/flutter (23830):      at com.builttoroam.devicecalendar.DeviceCalendarPlugin.parseEventArgs(DeviceCalendarPlugin.kt:151)
I/flutter (23830):      at com.builttoroam.devicecalendar.DeviceCalendarPlugin.onMethodCall(DeviceCalendarPlugin.kt:108)
I/flutter (23830):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter (23830):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
I/flutter (23830):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
I/flutter (23830):      at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (23830):      at android.os.MessageQueue.next(MessageQueue.java:335)
I/flutter (23830):      at android.os.Looper.loop(Looper.java:183)
I/flutter (23830):      at android.app.ActivityThread.main(ActivityThread.java:7664)
I/flutter (23830):      at java.lang.reflect.Method.invoke(Native Method)
I/flutter (23830):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
I/flutter (23830):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter (23830): )
I/flutter (23830): null

**MY CODE:**
import 'package:flutter/material.dart';
import 'package:device_calendar/device_calendar.dart';
import 'package:timezone/timezone.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late DeviceCalendarPlugin _deviceCalendarPlugin;

  void _createTestEvent() async {
    _deviceCalendarPlugin = DeviceCalendarPlugin();

    Event _myEvent = Event(
        '15',
        title: 'My test-event',
        start: TZDateTime.local(2021, 7, 13, 17, 00),
        end: TZDateTime.local(2021, 7, 13, 17, 30),
        availability: Availability.Tentative);

    final result = await _deviceCalendarPlugin.createOrUpdateEvent(_myEvent);
    print(result?.data);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FloatingActionButton(
              onPressed: () {
                _createTestEvent();
              },
              child: Icon(Icons.add),
            ), 
          ],
        ),
      ),
    );
  }
}
E:

**Comment by thomassth** [comment] 2021-07-13 17:53
Did you get this error from the version from github-clone? (also, which branch and/or release?) or prerelease from pub.dev?

**Comment by severin13** [comment] 2021-07-13 18:02
Sorry, forgot to mention that, this error occurs with the device_calendar 4.0.1-dev.13167 prerelease from pub.dev.

**Comment by miri-red** [comment] 2021-09-04 19:00
same here - the prerelease from pub.dev, same error. Was there any solution found?

**Comment by thomassth** [comment] 2021-12-18 18:37
Can't reproduce. Closing this for now.

If you encounter this issue again on latest release / dev branch please provide your steps to reproduce.

**Closed by thomassth** 2021-12-18 18:37 UTC
Labels: bug, more information required
