### ISSUE TITLE
result from retrieveCalendars() returns id and name = null on Android

### ISSUE THREAD

**Issue by chuckinSpace** [builttoroam/device_calendar#217] opened 2020-04-03 13:47 UTC
Only on Android (IOS is working fine, same code), I'm getting back a non-empty array with the right amount of calendars (length 2), but the actual fields are all null, (id, name etc..) any ideas? permissions are granted correctly, I tried both on the simulator and on a real device

` final calendarsResult = await _deviceCalendarPlugin.retrieveCalendars();`

![Screen Shot 2020-04-03 at 9 45 00 AM](https://user-images.githubusercontent.com/28461538/78367332-e6224480-758f-11ea-9e10-5db20c7386cd.png)

![Screen Shot 2020-04-03 at 10 14 59 AM](https://user-images.githubusercontent.com/28461538/78370015-0eac3d80-7594-11ea-9c7b-91ef13b75ec3.png)

**Comment by chuckinSpace** [comment] 2020-04-03 23:34
Well after starting from a brand new project I figured out what was wrong,  I was running into this issue  https://github.com/flutter/flutter/issues/47517  after I added google sign in, and tried to fix it with  one of the accepted answers ===>
```
buildTypes {
        release {
         signingConfig signingConfigs.debug
            minifyEnabled true
        }
        debug{
            minifyEnabled true
        }
    }
```
This created the conflict with device Calendar and start to get back null results, I fixed it using the other solution from the issue

Add this to defaultConfig
```
multiDexEnabled true
```
That one fixed the original issue and don't mess with device calendar

**Comment by Brett09** [comment] 2020-04-06 01:01
We had similar issues previously on release mode, if related, you might want to check the Proguard settings for Android [here](https://github.com/builttoroam/device_calendar/issues/99).

**Comment by chuckinSpace** [comment] 2020-04-11 15:02
Yes, I am actually getting that issue now, waiting for some feedback on that there

**Comment by devs4522** [comment] 2020-04-13 07:18
I am also facing same issue in release apk only even after applying above changes. Please help if anyone faced and resolved it before. Thanks

**Comment by devs4522** [comment] 2020-04-13 08:41
I got it resolved by following Proguard settings. @Brett09 Could you please remove - if you have Proguard enabled, from the readme page because it is confusing . most of new developer dont know whether it is enabled for their project or not. So Make  it a mandatory steps rather than optional in installation of this library.

**Comment by mmc16** [comment] 2020-05-25 13:32
I'm getting the same issue. I'm new to app development and AFAIK I'm not using Proguard (I couldn't find any proguard file), and what @chuckinSpace suggested didn't work for me either....
Am I missing something?

**Comment by nickrandolph** [comment] 2020-06-06 23:29
@devs4522 can you suggest the changes to the readme that you'd like to see w.r.t. Proguard settings.
@mmc16 are you seeing this issue in both debug and release?

**Comment by mmc16** [comment] 2020-06-08 12:16
I solved this issue following [this](https://github.com/builttoroam/device_calendar/issues/99#issuecomment-612449677) comment.

**Comment by PauloBrazilDHPP** [comment] 2020-09-22 02:38
i have the same issue and tried all solutions listed here... nothing worked
when compiled directly on device, it works well... when i submmit to play console, when install the beta on any device doesnt work... any other idea?

**Comment by maerlynflagg** [comment] 2021-03-24 14:04
> i have the same issue and tried all solutions listed here... nothing worked
> when compiled directly on device, it works well... when i submmit to play console, when install the beta on any device doesnt work... any other idea?

yeah same. Windows Android Emulator, all fine. debugging on real device fine. but a release build in Play Store is not working, cause missing or invalid calendar id.

**Comment by thomassth** [comment] 2021-04-26 15:44
@PauloBrazilDHPP and @maerlynflagg , can you confirm that you added the appropriate proguard settings?
[https://github.com/builttoroam/device_calendar#proguard--r8-exceptions](https://github.com/builttoroam/device_calendar#proguard--r8-exceptions)

**Comment by maerlynflagg** [comment] 2021-04-27 06:11
> @PauloBrazilDHPP and @maerlynflagg , can you confirm that you added the appropriate proguard settings?
> https://github.com/builttoroam/device_calendar#proguard--r8-exceptions

yes i can confirm, that is fixed, after i made a proguard on 25 Mar.

this helped me:

```
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }

#Plugins
-keep class com.builttoroam.devicecalendar.** { *; }
```

**Closed** 2021-04-27 06:35 UTC
Labels: more information required
